spring.application.name=EventCalendar

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=event_calendar;instanceName=SQLEXPRESS;
spring.datasource.username=sa
spring.datasource.password=pa55word
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2008Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
